### ISSUE TITLE
www.maigoo.com这个网站无法使用

### ISSUE THREAD

**Issue by LilQit7** [WindrunnerMax/TKScript#101]

**Comment by WindrunnerMax** [comment]
可以发个具体的链接

或者使用用通用版本处理这个问题 文本选中复制-通用 [详情](https://github.com/WindrunnerMax/TKScript/blob/master/packages/copy-currency/README.md) [安装](https://windrunnermax.github.io/TKScript/copy-currency.user.js)，注意看详情使用信息，需要左下角手动开启才可以
