### ISSUE TITLE
CSDN网页搜索栏会不断被隐藏和显示，导致页面抖动

### ISSUE THREAD

**Issue by FlandreSatori** [WindrunnerMax/TKScript#102]
https://github.com/WindrunnerMax/TKScript/assets/110801100/3cd46ff2-4aee-40b2-91eb-e3d07908107e

**Comment by WindrunnerMax** [comment]
我没能复现这个问题，这应该不是这个插件造成的问题，可以尝试逐个禁用插件测试下

**Comment by FlandreSatori** [comment]
😂我的插件显示我启用了4个脚本，但实际上只有1个。无论如何，我发现我也没办法复现这个问题。下次再遇到的话会排查一下的。

**Comment by WindrunnerMax** [comment]
哈哈哈哈，可能就是csdn自己的BUG而已
