### ISSUE TITLE
知乎专栏的请求支持

### ISSUE THREAD

**Issue by no-surprise-for-me** [WindrunnerMax/TKScript#106]
支持知乎，但不支持知乎专栏，比如：https://zhuanlan.zhihu.com/p/259583430

**Comment by WindrunnerMax** [comment]
我测试这个链接不启动插件也能正常复制？

**Comment by Widecss** [comment]
貌似 Firefox 是可以正常复制的，而 Chrome 和 Edge 不行，三者的测试都是在未登录下进行。

**Comment by WindrunnerMax** [comment]
看起来我测试可以复制是因为我已经登录了

**Comment by WindrunnerMax** [comment]
已支持，需要`6.1.17`版本
