### ISSUE TITLE
请求对CSDN文库添加支持

### ISSUE THREAD

**Issue by pyxherb** [WindrunnerMax/TKScript#108]
CSDN可以复制 但CSDN文库不行
网址：https://www.baidu.com/link?url=obnjxOUHrGFWe8NEZpZobiF1_FVEEe8Oh9rMzJ270M9x31pVJR3M7ch-Dg8O5zI5IuX9eTubwELxI-GowQ-uC0l9ojZFN7leP_Z4bySoWNy&wd=&eqid=df1fbda5000de3120000000364be8cf6

**Comment by WindrunnerMax** [comment]
已更新，需要`6.1.18`版本
