### ISSUE TITLE
希望添加对b站笔记的支持

### ISSUE THREAD

**Issue by qlqw233** [WindrunnerMax/TKScript#109]

**Comment by WindrunnerMax** [comment]
可以先发个链接

**Comment by qlqw233** [comment]
来晚了，https://www.bilibili.com/video/BV13e4y1s7Xa/ 以这个视频作为示例，点开视频下面的笔记，到笔记详情，可以发现笔记文本无法复制

**Comment by WindrunnerMax** [comment]
不是很懂，你可以直接把笔记详情的链接发一下就可以了
