### ISSUE TITLE
知乎“文章”全屏，点击“评论”——页面左移一点点、无法弹出“评论”弹窗、无法显示原网页的评论列表中存在的评论

### ISSUE THREAD

**Issue by Li-Enkuo** [WindrunnerMax/TKScript#110]
知乎“文章”全屏，点击“评论”——页面左移一点点、无法弹出“评论”弹窗、无法显示原网页的评论列表中存在的评论

**Comment by Dome-World** [comment]
我这里也出现了这个错误

**Comment by WindrunnerMax** [comment]
可以给个链接提供下完整的复现路径，在我这里没有复现

**Comment by Li-Enkuo** [comment]
> 可以给个链接提供下完整的复现路径，在我这里没有复现

复现环境：

Edge 浏览器、篡改猴扩展、“文件选中复制”扩展

复现步骤：

1.准备好复现环境

2.打开并登录“知乎” -> 在“首页”中稍微下滚，在右下角找到“专栏”并点击进去 -> 随便进入某一个专栏 -> 随便选中某个专栏的“文章”标题，进入全屏页面显示的“文章”

（第 2 步较繁琐，可直接由链接直达：https://zhuanlan.zhihu.com/p/79548362）

3.在未展开”评论“列表时，直接点击” x 条评论“按钮，如下图。

![image](https://github.com/WindrunnerMax/TKScript/assets/141030620/9f5ab802-1acb-4314-bf91-d8978472d397)

发现问题：

1.整个网页页面左移了一点点，并且原本应该弹出的”评论“窗口也不会弹出。

2.往下滚动，会发现，在” x 条评论“按钮下，原本应该显示出来的”评论“列表，也没有显示出来了。

**Comment by Li-Enkuo** [comment]
> 已修复，需要`6.1.19`版本

哇哦，好开心！！！
