### ISSUE TITLE
请问一下各位，腾讯文档是怎么做到复制的？为啥其他方法都是失效的，暂时只看到这个方法？

### ISSUE THREAD

**Issue by tangchuqi** [WindrunnerMax/TKScript#111]
打印，保存本地，F12，各种代码，IE不让访问的。
例如https://docs.qq.com/doc/DQmx1WEdTRXpGeEZ6

**Comment by tangchuqi** [comment]
这个脚本是生效的，不过得在其他地方点一下，才能出现“复制”的按钮

**Comment by WindrunnerMax** [comment]
需要点击其他位置的BUG已修复，实现方式可以直接参考源码，欢迎提PR
