### ISSUE TITLE
可以增加对腾讯文档复制的支持嘛

### ISSUE THREAD

**Issue by vonzs** [WindrunnerMax/TKScript#113]

**Comment by WindrunnerMax** [comment]
如果不支持的话可以发个可以直接访问并且不能复制的链接

**Comment by yizhifangyuan** [comment]
https://docs.qq.com/sheet/DVGFNSEh3dUdjY0xY?tab=BB08J2     可以试试这个限制的文档 权限是可查看禁止复制 这种文档 脚本不太支持 希望大佬看下

**Comment by yizhifangyuan** [comment]
![image](https://github.com/WindrunnerMax/TKScript/assets/19235127/4cc29177-cad4-4819-b5cf-2a9ab4db69a6)
大佬高效率  https://docs.qq.com/sheet/DVGFNSEh3dUdjY0xY?tab=BB08J2 还是这个文档 里面对链接的解析结果有待优化  目前是读取为object
