### ISSUE TITLE
可以支持一下魔镜歌词网么https://mojim.com/

### ISSUE THREAD

**Issue by Melatoninxx** [WindrunnerMax/TKScript#114]
🙏多谢！

**Comment by Melatoninxx** [comment]
https://mojim.com/cnznew.htm

他有中文和英文的

**Comment by WindrunnerMax** [comment]
我试了下是可以复制的吧

**Comment by Melatoninxx** [comment]
歌词的部分是不可以的
https://mojim.com/cny100663x27x1.htm

Czy ***@***.***> 于2023年9月8日周五 19:13写道：

**Comment by WindrunnerMax** [comment]
<img width="718" alt="image" src="https://github.com/WindrunnerMax/TKScript/assets/33169019/1a3840c0-c425-4e99-8c23-a7d0cfedfbd1">


我这边试着没啥问题

**Comment by Melatoninxx** [comment]
那好奇怪，我这还是不可以的

Czy ***@***.***> 于2023年9月8日周五 20:20写道：

**Comment by WindrunnerMax** [comment]
试试这个插件吧

<img width="828" alt="image" src="https://github.com/WindrunnerMax/TKScript/assets/33169019/3a8fafc0-7736-4152-a04a-a65bc59e3e5c">

**Comment by Melatoninxx** [comment]
也是不行，我是mac M2 Pro 13.4.1，chrome版本 116.0.5845.140（正式版本） (arm64)

Czy ***@***.***> 于2023年9月8日周五 20:49写道：

**Comment by WindrunnerMax** [comment]
这个插件你得在左下角那个蓝色的区域手动开启

https://github.com/WindrunnerMax/TKScript/blob/master/packages/copy-currency/README.md

**Comment by WindrunnerMax** [comment]
或者试试浏览器扩展https://github.com/WindrunnerMax/TKScript/blob/master/packages/force-copy/README.md
