### ISSUE TITLE
遇到问题先读这篇文章！！！

### ISSUE THREAD

**Issue by Firedoge1** [WindrunnerMax/TKScript#116]
https://mp.weixin.qq.com/s/pw6fQoZaCMWhz_5A5_hp1g

**Comment by WindrunnerMax** [comment]
文章写得不错，只是你最后介绍的那个拓展，我发现大量引用了我的打包过后的GPL协议的代码而没有任何版权和开源的标注，让我很尴尬

<img width="638" alt="image" src="https://github.com/WindrunnerMax/TKScript/assets/33169019/ee127e8e-2244-4187-a380-868eea4d47cf">

<img width="662" alt="image" src="https://github.com/WindrunnerMax/TKScript/assets/33169019/580eebec-21d8-495d-8b5b-0b888223f08b">

**Comment by Firedoge1** [comment]
这不是我写的

**Comment by Firedoge1** [comment]
所以这个扩展没有上架Firefox
