### ISSUE TITLE
网页版有道云笔记异常

### ISSUE THREAD

**Issue by fang-zhuoqun** [WindrunnerMax/TKScript#119]
打开插件进入网页版有道云笔记时出现异常，编辑用的字符光标无法显示。

**Comment by WindrunnerMax** [comment]
我试了试好像还好，可以发个链接看看？具体是编辑什么类型

**Comment by fang-zhuoqun** [comment]
网址是 note点youdao点com ，登录后请点击右上角的“切换到新版本”，问题就可以复现了。

**Comment by WindrunnerMax** [comment]
<img width="466" alt="image" src="https://github.com/WindrunnerMax/TKScript/assets/33169019/71e888ab-76ad-493b-9b22-44b196c49ff4">

没看到有切换到新版版

**Comment by liuweilhy** [comment]
确实跟有道云笔记的网页版本有冲突，造成有道云笔记不能正常复制文字。

**Comment by WindrunnerMax** [comment]
已修复，需要6.1.23版本
