### ISSUE TITLE
能不能支持小说网站比如起点？

### ISSUE THREAD

**Issue by Remonli** [WindrunnerMax/TKScript#12]
一大波小说网站都禁止右键复制，能不能考虑支持一下？谢谢！

**Comment by WindrunnerMax** [comment]
可以给个链接

**Comment by Remonli** [comment]
https://read.qidian.com/chapter/YXWyj4rRK3haXyNuGKajlg2/fvvofXUbBE1p4rPq4Fd4KQ2/
https://vipreader.qidian.com/chapter/1026665428/656543421/
分别是起点免费版和收费版的地址
http://book.zongheng.com/chapter/1149914/66727488.html
纵横
http://www.17k.com/chapter/1592435/22901241.html
17k
https://www.ciweimao.com/chapter/107555867
刺猬猫
https://book.qq.com/book-read?bid=40727444&cid=1&checkRH=1
QQ读书

这几个是常用的网文站了，其他更小众我就没写。
