### ISSUE TITLE
【BUG MAYBE】豆丁，多页情况下无法点击“展开继续阅读”

### ISSUE THREAD

**Issue by lukaschan** [WindrunnerMax/TKScript#120]
无论是油猴脚本还是FORCE COPY扩展，多页情况下，无法点击“展开继续阅读”。

![WeChat截图_20231208110017](https://github.com/WindrunnerMax/TKScript/assets/3959525/617e0794-c9d7-418f-a6db-8c60802901cc)

**Comment by WindrunnerMax** [comment]
确实有点问题，不过即使点击了也会弹窗要登录
<img width="829" alt="image" src="https://github.com/WindrunnerMax/TKScript/assets/33169019/7f73a2f8-6ae7-4b2f-96f6-0a7a403696c0">

**Comment by lukaschan** [comment]
有时会弹窗要求登陆，有时不弹窗

**Comment by WindrunnerMax** [comment]
我测试了一下，关闭所有插件，如果先切换为文本状态 

<img width="231" alt="image" src="https://github.com/WindrunnerMax/TKScript/assets/33169019/c07aa4be-2e59-47ee-959b-565ec739f221">

然后选中几个文字，之后再点击继续阅读，就可以复现这个问题，这是他这个网站本身的问题了
