### ISSUE TITLE
某歌词网站不起效）

### ISSUE THREAD

**Issue by De-Xiao** [WindrunnerMax/TKScript#121]
https://www.lyrical-nonsense.com/lyrics/ayafubumi/onionikonkonwaon/

**Comment by WindrunnerMax** [comment]
可以使用扩展 https://github.com/WindrunnerMax/TKScript/blob/master/packages/force-copy/README.md

**Comment by De-Xiao** [comment]
多谢

Czy ***@***.***> 于2024年1月2日周二 22:01写道：
