### ISSUE TITLE
请求对金山kdocs复制的支持

### ISSUE THREAD

**Issue by tangchuqi** [WindrunnerMax/TKScript#122]
作者你好，样例如下
https://www.kdocs.cn/l/crpqQlvLvCuN

**Comment by WindrunnerMax** [comment]
已支持，需要`6.1.24`版本

**Comment by tangchuqi** [comment]
> 已支持，需要`6.1.24`版本

你好，更新6.1.24后，我这边未登录状态下，还是没有预期弹出"复制"的蓝色选项。已试过清除缓存，重新安装脚本。
Win10 版本 5.0.1002.354（正式版本） （64 位） (Chromium 102.0.5005.167)

**Comment by WindrunnerMax** [comment]
直接 Ctrl C 复制即可

**Comment by tangchuqi** [comment]
> 直接 Ctrl C 复制即可

Ctrl+C也是弹出"没有复制权限"，并且粘贴板内没有内容。尝试登录了金山，或者使用最新Chrome也是无效

**Comment by WindrunnerMax** [comment]
等我回去再看看，昨天我用着还是好的，可能是他又恰好发了新版本

**Comment by tangchuqi** [comment]
> 等我回去再看看，昨天我用着还是好的，可能是他又恰好发了新版本

感谢大佬，有空帮忙看看哈，坐等更新

**Comment by WindrunnerMax** [comment]
试试 6.1.25

**Comment by tangchuqi** [comment]
> 试试 6.1.25

感谢大佬，问题已解决，可以右键复制或者Ctrl+C复制了
