### ISSUE TITLE
网页版的小宇宙无法复制了

### ISSUE THREAD

**Issue by 954708775** [WindrunnerMax/TKScript#125]
以前小宇宙打开可以复制文本，现在无法复制，准确的说无法选中，有没有好办法来解决呢

**Comment by 954708775** [comment]
> 可以放个链接我适配一下

https://www.xiaoyuzhoufm.com/episode/64ddfd4ae490c5dee5b7ae21

**Comment by WindrunnerMax** [comment]
已更新，需要 6.2.1 版本，也可以尝试使用扩展 https://github.com/WindrunnerMax/TKScript/blob/master/packages/force-copy/README.md
