### ISSUE TITLE
请求新增网站支持

### ISSUE THREAD

**Issue by Kagura-Nanaa** [WindrunnerMax/TKScript#126]
网站名为火山引擎，该网站搜索内容复制需要登录下面是链接
https://www.volcengine.com/theme/3989165-A-7-1

**Comment by WindrunnerMax** [comment]
火山可以直接用拓展 https://github.com/WindrunnerMax/TKScript/blob/master/packages/force-copy/README.md

**Comment by BradleyNotFound** [comment]
头歌平台需要麻烦适配一下：https://www.educoder.net/

**Comment by WindrunnerMax** [comment]
> 头歌平台需要麻烦适配一下：https://www.educoder.net/

需要一个直接可访问的不可复制链接，建议先用扩展试试
