### ISSUE TITLE
请求支持网站【知识星球】

### ISSUE THREAD

**Issue by DoubleW2w** [WindrunnerMax/TKScript#129]
在一些付费的知识星球中，星主发布的文章是不允许复制的。[https://wx.zsxq.com/](https://wx.zsxq.com/)

**Comment by WindrunnerMax** [comment]
没有具体的地址是测试不了的，或者可以试试用 README 提供的浏览器扩展

**Comment by DoubleW2w** [comment]
> 没有具体的地址是测试不了的，或者可以试试用 README 提供的浏览器扩展

好的，谢谢你的回答。

**Comment by WindrunnerMax** [comment]
客气
