### ISSUE TITLE
好多都失效不能复制了

### ISSUE THREAD

**Issue by qzstudio** [WindrunnerMax/TKScript#130]
https://www.php.cn/faq/464298.html
https://blog.51cto.com/u_14502478/6397462

**Comment by WindrunnerMax** [comment]
可以试试扩展程序 https://github.com/WindrunnerMax/TKScript/blob/master/packages/force-copy/README.md

**Comment by qzstudio** [comment]
可以复制了  但是这扩展每个站点都要设置一遍、  能全局设置吗？而且那个编辑框右上角的复制还未实现

**Comment by WindrunnerMax** [comment]
通常来说解除限制是有一定风险破坏网站原本功能的，所以按需取用是合理的，此外右上角的编辑框之类的不在处理范围

**Comment by qzstudio** [comment]
那这个能加一个开启的名单不？自己往里面添加需要开启的站点域名

**Comment by WindrunnerMax** [comment]
另外忘了说了，这个扩展是域名级的记录，也就是说在某个域名开启以后访问别的地址也是一直开启的，除非清缓存
