### ISSUE TITLE
请求支持腾讯文档幻灯片的文字复制

### ISSUE THREAD

**Issue by laymanal** [WindrunnerMax/TKScript#134]
示例链接：[https://docs.qq.com/slide/DTHhJbmxma1dlbU1z](https://docs.qq.com/slide/DTHhJbmxma1dlbU1z)

**Comment by WindrunnerMax** [comment]
已支持

**Comment by laymanal** [comment]
Chrome 已经可以复制文字了，但我主用的 Firefox 还是不行，可否再处理一下，拜托了🙏
