### ISSUE TITLE
ForceCopy 使用 document.body.contentEditable

### ISSUE THREAD

**Issue by People-11** [WindrunnerMax/TKScript#135]
ForceCopy 功能请求
对于某些比较难办的网站，使用 document.body.contentEditable = true 是一个简单粗暴的方法，希望在扩展中添加此备选方法

**Comment by People-11** [comment]
此外，解除键盘限制功能在此js中无法解除F12限制，作者可以参考一下

```
function Z() { var n = 73,
                e = 85,
                t = 83,
                o = 123,
                i = c ? function(e, t) { return e.metaKey && e.altKey && t === n } : function(e, t) { return e.ctrlKey && e.shiftKey && t === n },
                r = c ? function(n, o) { return n.metaKey && n.altKey && o === e || n.metaKey && o === t } : function(n, o) { return n.ctrlKey && (o === t || o === e) };
            window.addEventListener("keydown", (function(n) { var e = (n = n || window.event).keyCode || n.which; if (e === o || i(n, e) || r(n, e)) return n.returnValue = !1, n.preventDefault(), !1 }), !0), F.disableMenu && q(window, "contextmenu"), F.disableSelect && q(window, "selectstart"), F.disableCopy && q(window, "copy"), F.disableCut && q(window, "cut") }
```

**Comment by WindrunnerMax** [comment]
> 此外，解除键盘限制功能在此js中无法解除F12限制，作者可以参考一下
> 
> ```
> function Z() { var n = 73,
>                 e = 85,
>                 t = 83,
>                 o = 123,
>                 i = c ? function(e, t) { return e.metaKey && e.altKey && t === n } : function(e, t) { return e.ctrlKey && e.shiftKey && t === n },
>                 r = c ? function(n, o) { return n.metaKey && n.altKey && o === e || n.metaKey && o === t } : function(n, o) { return n.ctrlKey && (o === t || o === e) };
>             window.addEventListener("keydown", (function(n) { var e = (n = n || window.event).keyCode || n.which; if (e === o || i(n, e) || r(n, e)) return n.returnValue = !1, n.preventDefault(), !1 }), !0), F.disableMenu && q(window, "contextmenu"), F.disableSelect && q(window, "selectstart"), F.disableCopy && q(window, "copy"), F.disableCut && q(window, "cut") }
> ```

可以发个地址看一下？

**Comment by People-11** [comment]
> > 此外，解除键盘限制功能在此js中无法解除F12限制，作者可以参考一下
> > ```
> > function Z() { var n = 73,
> >                 e = 85,
> >                 t = 83,
> >                 o = 123,
> >                 i = c ? function(e, t) { return e.metaKey && e.altKey && t === n } : function(e, t) { return e.ctrlKey && e.shiftKey && t === n },
> >                 r = c ? function(n, o) { return n.metaKey && n.altKey && o === e || n.metaKey && o === t } : function(n, o) { return n.ctrlKey && (o === t || o === e) };
> >             window.addEventListener("keydown", (function(n) { var e = (n = n || window.event).keyCode || n.which; if (e === o || i(n, e) || r(n, e)) return n.returnValue = !1, n.preventDefault(), !1 }), !0), F.disableMenu && q(window, "contextmenu"), F.disableSelect && q(window, "selectstart"), F.disableCopy && q(window, "copy"), F.disableCut && q(window, "cut") }
> > ```
> 
> 可以发个地址看一下？

https://boke112.com/article/cloudflare-brotli-auto-minify.html

**Comment by WindrunnerMax** [comment]
F12 这个键盘事件后边会处理好，清空 console 这个就不在处理范围了，另外加入 contentEditable 这种增强的破坏性功能我得考虑下如何做交互

**Comment by WindrunnerMax** [comment]
可以举个 contentEditable 能够解决问题的网站吗

**Comment by People-11** [comment]
> 可以举个 contentEditable 能够解决问题的网站吗

目前还没有，或者曾经有但我没想起来，我是鉴于 contentEditable 实在是简单粗暴，而建议其作为一个额外功能/可选方案

**Comment by WindrunnerMax** [comment]
FireFox 已经更新，Chrome 审核需要的时间会比较长
