### ISSUE TITLE
复制leetcode题解代码块没有适配

### ISSUE THREAD

**Issue by Fanyu911** [WindRunnerMax/TKScript#141]
## 问题描述

leetcode的题解代码块没有生效

<img width="1084" alt="image" src="https://github.com/user-attachments/assets/f13d67db-98f1-4849-9195-f2a2f9179807">

## 项目所属

- [ ] Copy
- [ ] Force Copy
- [ ] Copy Currency
- [ ] Site Director
- [ ] Captcha
- [ ] Expansion
- [ ] Completion
- [ ] Unknown

## 相关链接

相关路径leetcode.cn/problems/search-suggestions-system/solutions

**Comment by WindRunnerMax** [comment]
done
