### ISSUE TITLE
ForceCopy 会导致在 Firefox 中打开的 xml 文件开头多出一段 JavaScript 代码

### ISSUE THREAD

**Issue by 0x391F** [WindRunnerMax/TKScript#143]
## 问题描述

ForceCopy 会导致在 Firefox 中打开的 xml 文件开头多出一段 JavaScript 代码

![启用ForceCopy扩展](https://github.com/user-attachments/assets/c9118f35-94fc-4161-84a5-3019e9b15f26)
![禁用ForceCopy扩展](https://github.com/user-attachments/assets/ba91cebb-c9bb-401c-8077-fec9bb687d66)

## 项目所属

- [ ] Copy
- [x] Force Copy
- [ ] Copy Currency
- [ ] Site Director
- [ ] Captcha
- [ ] Expansion
- [ ] Completion
- [ ] Unknown

## 预期表现

不应该出现这个问题

**Comment by 0x391F** [comment]
[eap.xml.txt](https://github.com/user-attachments/files/17992784/eap.xml.txt)
此文件后缀名删掉 .txt

**Comment by WindRunnerMax** [comment]
待会我处理一下

**Comment by 0x391F** [comment]
已解决，谢谢！
Fixed, thanks!

**Comment by 0x391F** [comment]
现在 xml 文件没有问题了，但是又导致 https://www.realtek.com/Download/List?cate_id=584 无法正常加载。。。

**Comment by WindRunnerMax** [comment]
在 FF 里有个因为 CSP 策略而导致 inject script 执行失败的问题 https://github.com/violentmonkey/violentmonkey/issues/1001，是这里影响的，但是看起来不可靠，还是先去掉这块处理策略吧

**Comment by WindRunnerMax** [comment]
@0x391F 再升级一下吧 1.0.10 版本

**Comment by 0x391F** [comment]
现在两个都可以了，谢谢啦
