### ISSUE TITLE
希望支持腾讯文档的复制

### ISSUE THREAD

**Issue by HonkerForce** [WindrunnerMax/TKScript#16]
腾讯文档设置只读模式，不能复制，希望可以kill掉TX

**Comment by WindrunnerMax** [comment]
请提供个链接，不过之前我记得弄过这个玩意，没解决这个比较难顶

**Comment by HonkerForce** [comment]
https://docs.qq.com/doc/DWmhmRVdnbW9Oemhj

https://docs.qq.com/doc/DWlFIVE1vQ1NtTGNO

(ง •_•)ง

**Comment by HonkerForce** [comment]
CS17 基于数据库和GUI的教务管理系统 (qq.com)感谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年11月15日(星期一) 上午10:54
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [WindrunnerMax/TKScript] 希望支持腾讯文档的复制 (Issue #16)





 
请提供个链接，不过之前我记得弄过这个玩意，没解决这个比较难顶
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by HonkerForce** [comment]
https://docs.qq.com/doc/DY05IVnJaT29OeW9s?pub=1&friendUin=8ZYowWphLlSN7HDp2GabcQ%25253D%25253D&ADUIN=627226821&ADSESSION=1636942770&ADTAG=CLIENT.QQ.5651_.0&ADPUBNO=27156&jumpuin=627226821

感谢:pray:

**Comment by WindrunnerMax** [comment]
搞不了这个，这个太顶了😑

**Comment by HonkerForce** [comment]
我也是写程序的（虽然我不写脚本），顶在哪？有时间说说吗？:pray:




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年11月15日(星期一) 中午11:54
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [WindrunnerMax/TKScript] 希望支持腾讯文档的复制 (Issue #16)





 
搞不了这个，这个太顶了😑
 
&mdash;
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by WindrunnerMax** [comment]
首先他是`canvas`绘制的文档，其次他是`React`的自己的事件系统

**Comment by WindrunnerMax** [comment]
已修正，可以更新`3.0.4`版本

**Comment by HonkerForce** [comment]
牛逼，可以了，膜拜大佬:thumbsup::pray:
