### ISSUE TITLE
麻烦搞定知识星球这个网站：www.zsxq.com

### ISSUE THREAD

**Issue by mrchengcheng** [WindrunnerMax/TKScript#17]

**Comment by WindrunnerMax** [comment]
请直接提供一个无法复制的链接

**Comment by William12335** [comment]
https://wenku.baidu.com/view/98fe496885868762caaedd3383c4bb4cf6ecb739.html?rec_flag=default&fr=Recommend_RelativeDoc-100008,60273,100006,60308,40340,40397,60416,90016-kpdrec_doc_pc_view-84fd82c729ea81c758f5f61fb7360b4c2e3f2ada&sxts=1637800537748

**Comment by xiaoyichase** [comment]
https://www.tcm999.cn/content/id/93ed9cc10c22590102029dea

**Comment by xiaoyichase** [comment]
> https://www.tcm999.cn/content/id/93ed9cc10c22590102029dea

不用了，我发现了，这个网址输入这个js
document.body.oncopy=function(){
		$(".charging_box").css("display","none");
}就可以复制
