### ISSUE TITLE
腾讯文档现在变成无差别复制了，选中文本就会复制

### ISSUE THREAD

**Issue by 89x98** [WindrunnerMax/TKScript#18]
这个不能像百度文库一样做个弹出的复制按钮吗，有时候编辑文档会选中一段文字用别的粘贴的文字替换掉，现在选中一段文字就直接就把之前复制的文字盖掉了

**Comment by WindrunnerMax** [comment]
这应该是我实现的一个失误，我尽快修正一下

**Comment by WindrunnerMax** [comment]
已处理，可以更新`3.0.6`版本
