### ISSUE TITLE
能不能适配一下瑞文网

### ISSUE THREAD

**Issue by lrlye** [WindrunnerMax/TKScript#19]
https://mip.ruiwen.com/gongzuojihua/1031369.html
这是其中的一个网站 一复制就要验证码 麻烦你了 谢谢 
https://mip.ruiwen.com/
这是他的主网站 谢谢

**Comment by WindrunnerMax** [comment]
已更新，请安装`3.0.8`版本

**Comment by lrlye** [comment]
谢谢谢谢

**Comment by WindrunnerMax** [comment]
客气了
