### ISSUE TITLE
快速复制

### ISSUE THREAD

**Issue by Rovever** [WindrunnerMax/TKScript#2]
有什么办法在网页表格旁边添加一个按钮，点击就能复制，省去选择文本的步骤了。

**Comment by WindrunnerMax** [comment]
这样大概是不好实现，很多表格不一定是`<table>`标签实现的，有很多用`<div> + CSS`实现，这样就比较难去确定这是个表格还是个啥

**Comment by Rovever** [comment]
如果只处理<table>标签带class属性的表格会很难吗，平时有比较多的复制表格操作，求大神指点

**Comment by WindrunnerMax** [comment]
我觉得用js直接处理表格内容的话应该会导致样式失效，用自己选中的是可以复制表格样式的，另外我也是小菜鸡一枚

**Comment by Rovever** [comment]
能做出这个你已经很厉害啦，解除网站复制限制很实用

**Comment by WindrunnerMax** [comment]
哈哈，做这个的主要原因是拦着我抄报告了，没办法了，先磨刀不误砍柴工
