### ISSUE TITLE
百度文库部分链接无法使用

### ISSUE THREAD

**Issue by Airi-star** [WindrunnerMax/TKScript#21]
链接如下
https://wenku.baidu.com/view/a715ffc16d85ec3a87c24028915f804d2b1687a0.html

https://wenku.baidu.com/view/beaf051ac281e53a5902ff03.html?rec_flag=default&fr=Recommend_RelativeDoc-90019,80014,60273,40408,60308,90018,60416,60418,110010-kpdrec_doc_pc_view-a715ffc16d85ec3a87c24028915f804d2b1687a0&sxts=1639190582699

**Comment by WindrunnerMax** [comment]
![image](https://user-images.githubusercontent.com/33169019/145661811-1fad91f2-3f61-4c6e-b869-4000613b430e.png)

我尝试好像没有问题，刷新一下试试？

**Comment by Airi-star** [comment]
https://user-images.githubusercontent.com/95949101/145662281-2d75faf7-3e4d-4fdb-b198-adfa364b5a14.mp4

单击选中时没有/复制/的悬浮窗，采用双击保持第二下不松开的情况下选中有弹窗，但复制后无文本内容

**Comment by WindrunnerMax** [comment]
你这个不是谷歌浏览器吧

**Comment by Airi-star** [comment]
不是，使用了Microsoft Edge，是否需要安装谷歌呢？

**Comment by WindrunnerMax** [comment]
要不试一下谷歌浏览器吧，这种浏览器兼容性问题很头疼

**Comment by WindrunnerMax** [comment]
#22 也同样出现了这个问题，你可以看看这个方案是否奏 https://github.com/WindrunnerMax/TKScript/issues/22#issuecomment-998808467

**Comment by WindrunnerMax** [comment]
请更新`3.0.10`版本，应该是正常了
