### ISSUE TITLE
百度文库选中文字无法复制，双击页面会出现复制按钮，点击复制，粘贴后为空

### ISSUE THREAD

**Issue by sjy6666** [WindrunnerMax/TKScript#22]

**Comment by sjy6666** [comment]
链接如下：
https://wenku.baidu.com/view/2e7551fb814d2b160b4e767f5acfa1c7ab008253.html

**Comment by sjy6666** [comment]
选中文字后不会跳出复制按钮

**Comment by WindrunnerMax** [comment]
是用的`edge`吧，试试用`Chrome`浏览器

**Comment by WindrunnerMax** [comment]
另外考虑是不是脚本冲突了，我这是没问题的

![image](https://user-images.githubusercontent.com/33169019/146937452-129e571f-6522-499a-b604-09f68c9673af.png)

**Comment by sjy6666** [comment]
啊，我用的是chrome，另外就安装了两个插件
![image](https://user-images.githubusercontent.com/96479950/146938602-f4f59473-7968-497e-9cc7-ee74a4abcb1f.png)
之前都是可以正常使用的，没有冲突

**Comment by WindrunnerMax** [comment]
这个确实不应该冲突，你的油猴是啥版本啊，我装一个看看

**Comment by sjy6666** [comment]
![image](https://user-images.githubusercontent.com/96479950/146939309-3c507476-e928-4396-b68b-b054d042bdbc.png)

**Comment by sjy6666** [comment]
![image](https://user-images.githubusercontent.com/96479950/146939906-b95a9b85-cf29-44c5-8253-34493e6b154c.png)

**Comment by WindrunnerMax** [comment]
你这是从哪扒拉的`4.5`版本，我看谷歌商店只到`4.13`啊

https://chrome.google.com/webstore/detail/tampermonkey/dhdgffkkebhmkfjojejmpbldmpobfkfo/related

**Comment by sjy6666** [comment]
21年四月份左右在官网下载的好像

**Comment by WindrunnerMax** [comment]
> 21年四月份左右在官网下载的好像

装Chrome官方商店的试试？

**Comment by WindrunnerMax** [comment]
我也更新一下chrome

**Comment by sjy6666** [comment]
道客巴巴啥的好像可以用，百度文库不行
http://www.doc88.com/p-68939064511025.html

**Comment by WindrunnerMax** [comment]
我更新了也没问题，这我真不知道为什么了，之前也有反馈这个问题的，我以为edge的问题，主要是无法复现，我没法处理他

**Comment by WindrunnerMax** [comment]
这样吧，你按F12，在控制台执行下这个，然后用Ctrl+C复制就行，我再看看这个问题。

```javascript
document.addEventListener("keydown", e => e.stopPropagation(), true);
```
![image](https://user-images.githubusercontent.com/33169019/146943209-5c1f338d-ae44-4adc-927f-5da76808e4ef.png)

**Comment by sjy6666** [comment]
好的，感谢

**Comment by WindrunnerMax** [comment]
先试试这个方案是不是可以应急用，如果有用的话明天我加到脚本里更新

**Comment by sjy6666** [comment]
![image](https://user-images.githubusercontent.com/96479950/146945983-98ee43a7-4f41-43f8-b059-fffd4bbcb213.png)
![image](https://user-images.githubusercontent.com/96479950/146946024-313b36f6-c026-49a9-923d-a90db7671cbe.png)

**Comment by WindrunnerMax** [comment]
我的意思是你执行了这个代码之后，你就可以直接选中文字内容然后按`Ctrl+C`复制了

**Comment by sjy6666** [comment]
大大，不行啊，偶尔复制成功一次还不知道复制到啥，驴唇不对马嘴

**Comment by WindrunnerMax** [comment]
那我就真不知道了，这看起来就很离谱了，等我明天更新一下脚本你再试试吧

**Comment by sjy6666** [comment]
Ueeshop_海外网站搭建+推广服务，助你收获询盘&订单
广告 独立站选Ueeshop，全球超过25500+跨境卖家选择，SaaS模式轻松简单搭建专业的跨境独立站， 查看详情 >

PayPal-免费b2b外贸平台必备，跨境贸易，随时随地
广告 Paypal与您共同成长，助您提升销量，提供超越支付的全方位服务，免费注册通道; 查看详情 >
PayPal--国际贸易网站支付必备
广告 海外贸易，广告联盟，网络营销必备，PayPal和贝宝是目前必备的海外及国内在线支付; 查看详情 >
196次复制
￥ 12 VIP特价购买
原价￥15

剩余3页未读，继续阅读
PayPal--国际贸易网站支付必备
4.03亿全球商家选择PayPal收付款，PayPal安全收款，轻松销售无国界，第三方支付必备;
广告查看详情
 版权说明：本文档由用户提供并上传，收益归属内容提供方，若内容存在侵权，请进行举报或认领
-------------------------------------------------**复制到了广告**大大 ------------------------------------------------------------------

**Comment by sjy6666** [comment]
好的，大大麻烦了

**Comment by WindrunnerMax** [comment]
更新一下`3.0.9`版本是试试吧，还是尝试下`Ctrl+C`复制，要是实在是不好使，我还处理了百度文库不让打印的问题，你可以尝试`Ctrl+P`然后在弹出来的页面去复制

**Comment by WindrunnerMax** [comment]
另外你那个是不是不是`Windows`机器啊

**Comment by sjy6666** [comment]
是windows，我在学校机器的chrome上装了，一样的油猴版本和插件版本，可以使用，好像是我浏览器的问题

**Comment by WindrunnerMax** [comment]
这就离谱了，看看这个试试

> 更新一下`3.0.9`版本是试试吧，还是尝试下`Ctrl+C`复制，要是实在是不好使，我还处理了百度文库不让打印的问题，你可以尝试`Ctrl+P`然后在弹出来的页面去复制

**Comment by sjy6666** [comment]
我现在搁机房上课，回去我试试在回复你吧

**Comment by WindrunnerMax** [comment]
哈哈哈好

**Comment by sjy6666** [comment]
大大，脚本对百度文库好像失效了，下午去机房就失效了（上午装插件的那台机子（没关机）），回来拿舍友的隔壁的都试了一下都不行，好像插件对百度文库失效了

**Comment by WindrunnerMax** [comment]
我用我另一台电脑试了一下，确实也出现了问题，我得研究一下到底哪里的问题，看起来是百度文库改版了，但是不知道为何我另一台电脑又没问题

**Comment by mxy25852** [comment]
我也是一样的没法选中后复制，看其他插件的说明好像是百度文库12.17更新了技术

**Comment by WindrunnerMax** [comment]
啊这不好整了，芭比Q了

**Comment by PeterShen666** [comment]
同遇到复制失效

**Comment by WindrunnerMax** [comment]
哪位尝试一下更新到`3.0.10`版本，然后试试能不能复制给我反馈一下

**Comment by WindrunnerMax** [comment]
`hack`了一下，能坚持多久便不得而知了

**Comment by PeterShen666** [comment]
3.0.10可以复制，但是在页面内在没有选中文字时单击也会出现复制按钮，此时点击按钮会复制部分标题文字

**Comment by WindrunnerMax** [comment]
> 3.0.10可以复制，但是在页面内在没有选中文字时单击也会出现复制按钮，此时点击按钮会复制部分标题文字

这块我也发现了，但是不好处理了，能复制已经不容易了，也不知道能坚持多久

**Comment by sjy6666** [comment]
👍

**Comment by WindrunnerMax** [comment]
现在这个改的极其恶心，不排除他会改的更恶心，怕是只能且用且珍惜了
