### ISSUE TITLE
www.baibeike.com无法复制

### ISSUE THREAD

**Issue by EVE06** [WindrunnerMax/TKScript#25]

**Comment by WindrunnerMax** [comment]
可以使用 https://greasyfork.org/zh-CN/scripts/439557 脚本，打开网站后点击油猴启动复制即可

![image](https://user-images.githubusercontent.com/33169019/152631184-f2275c6f-5dce-47c3-bc2d-e65471f8715a.png)

**Comment by WindrunnerMax** [comment]
已处理，可以使用原脚本也可以使用通用脚本，两者不冲突

**Comment by gushenwei** [comment]
@WindrunnerMax ，麻烦老师帮忙看一下 ，这个网站也不起作用；[https://www.jiucaigongshe.com/](url)，麻烦您了！
