### ISSUE TITLE
转载请求

### ISSUE THREAD

**Issue by CodFrm** [WindrunnerMax/TKScript#27]
大佬您好：

我是油猴中文网的管理员[王一之](https://bbs.tampermonkey.net.cn/home.php?mod=space&uid=4&do=profile)，我想将您的脚本：[文本选中复制](https://github.com/WindrunnerMax/TKScript/blob/master/dist/copy.js)、[跳转链接直达](https://github.com/WindrunnerMax/TKScript/blob/master/dist/site-director.js)，转载至我们的论坛：[油猴中文网](https://bbs.tampermonkey.net.cn/)，您看可以吗？

关于更新，我们会使用您的脚本链接设置自动同步在我们的论坛上进行更新。如果您不愿意创建账号，我们会将转载的脚本放在一个脚本搬运工的账号上，未来如果您愿意来论坛玩耍会把权限返还给您。

期待大佬的回复^_^。

关于我们论坛是一个油猴脚本的开发与交流的社区；同时我们也提供脚本的发布和安装，另外我们有开发一个新的类油猴扩展：脚本猫，除了支持油猴脚本外，还支持后台与定时脚本，更多的功能和接口还在开发中。

**Comment by WindrunnerMax** [comment]
当然可以，我刚注册了账号`WindrunnerMax`，接下来是不是就不再需要我个人操作了，另外还有 [文本选中复制-通用](https://github.com/WindrunnerMax/TKScript/blob/master/dist/copy-currency.js) 也可以考虑一下 🤣

**Comment by CodFrm** [comment]
🤣好的，我发布好后迁移到您的账号里面

**Comment by WindrunnerMax** [comment]
🤣 好的谢谢

**Comment by CodFrm** [comment]
处理啦

跳转链接直达
https://bbs.tampermonkey.net.cn/thread-1751-1-1.html
(出处: 油猴中文网)

文本选中复制
https://bbs.tampermonkey.net.cn/thread-1750-1-1.html
(出处: 油猴中文网)

文本选中复制(通用)
https://bbs.tampermonkey.net.cn/thread-1749-1-1.html
(出处: 油猴中文网)

**Comment by WindrunnerMax** [comment]
好嘞谢谢啦
