### ISSUE TITLE
百度文库无法选中复制

### ISSUE THREAD

**Issue by cs-note** [WindrunnerMax/TKScript#28]
百度文库无法选中复制，双击后出现复制按钮，复制后粘贴是空白

**Comment by WindrunnerMax** [comment]
可以先提供个链接

**Comment by cs-note** [comment]
比如这个：https://wenku.baidu.com/view/c559443e2bf90242a8956bec0975f46527d3a73a.html
无法选中复制

**Comment by WindrunnerMax** [comment]
我这还可以，你这个脚本是哪一个版本的

![image](https://user-images.githubusercontent.com/33169019/155827262-b4a21e11-a081-4c23-8b9d-d614a3825da1.png)

**Comment by cs-note** [comment]
3.1.4版本的，我也不知道什么原因，无法选中复制

**Comment by cs-note** [comment]
可以了，原来是另一个复制脚本失效了，被我不小心打开了，可能是导致冲突了，感谢作者

**Comment by WindrunnerMax** [comment]
好的，客气了
