### ISSUE TITLE
能否添加“解除知网HTML阅读复制”限制？

### ISSUE THREAD

**Issue by zhezhishang** [WindrunnerMax/TKScript#29]
[知网](https://www.cnki.net/)进行 HTML 在线阅读时，只能复制100字，登录后也只能复制300字，太残废了。

![1](https://user-images.githubusercontent.com/33953959/156882398-1205ebb4-ba46-4e51-9952-ab551ad99d17.png)

**Comment by WindrunnerMax** [comment]
你可以提供一个详细的链接

**Comment by zhezhishang** [comment]
> 你可以提供一个详细的链接

https://kns.cnki.net/KXReader/Detail?invoice=s%2FbfN2aZhZBX7yI0Hm2st3a0CtGXQyTDXaaEBBRikGDivQlfiIQ20vsP9xvhEHftRerhfOkEvAxseZF8fzEtLcXz8IjNqSleZsytKiCapV5xk92HfPSI1Oue8LW0fAgGq8cVL4mXcR%2B8zW4gwOD9suhg%2F82c8JxrXjOzW91xPkY%3D&DBCODE=CJFD&FileName=GWDZ202202038&TABLEName=cjfdlast2022&nonce=B29615AEA9084495B09C8DBFF901213A&uid=&TIMESTAMP=1646482885859
https://kns.cnki.net/KXReader/Detail?invoice=fRfRumXsKVHOp0yXW5FcGAithCpkRDtPEO6gISqqcqsI24oSfg2Ak8z7%2Bpt%2FZ0OiCqubD60mGA7LTv5GKKf6u%2Fp90tE01%2FVn4Mf4QS227h3G2Di4w8lDRZaOyyupnQZ%2BxZ9dQpJNfyewfcnXjxU%2F9chvcuqDldO6KzEcYlVaUjw%3D&DBCODE=CJFD&FileName=TSGJ202201011&TABLEName=cjfdlast2022&nonce=08D89C4767964B8FB93CEA7EEEE34DF5&uid=&TIMESTAMP=1646483048828
就这样的阅读页面，不知道你是否有权限访问知网

**Comment by WindrunnerMax** [comment]
我也是学生，知网还是能进的

**Comment by WindrunnerMax** [comment]
你更新一下`3.1.5`版本，可以试一下了，应该没问题了，别用他的复制，要不就是`ctrl c`要么右击复制

**Comment by zhezhishang** [comment]
> 你更新一下`3.1.5`版本，可以试一下了，应该没问题了，别用他的复制，要不就是`ctrl c`要么右击复制

可以了，很强！

**Comment by WindrunnerMax** [comment]
`ok`
