### ISSUE TITLE
百度文库的vip文档好像不好使

### ISSUE THREAD

**Issue by TigerZhao007** [WindrunnerMax/TKScript#3]
比如[这个](https://wenku.baidu.com/link?url=JFrZLtxjd90S2BwU5akCbwa1cd8uBQGH1rH27quW3TlE1PRwmshrchkjdwKQs5BKKu1tjmUxmTKEJCzIZHXBrZXqQOcbYimbsJE8kN_MlhGyGuD1xzqNTtq2jsknd2-HuF7IL9hmreNBRhbreFEZQ_)

**Comment by WindrunnerMax** [comment]
好的我看一下修复一下，应该是百度文库改东西了

**Comment by WindrunnerMax** [comment]
修复了，可以 [更新脚本](https://greasyfork.org/zh-CN/scripts/405130) 后试一下

**Comment by TigerZhao007** [comment]
Well done!
