### ISSUE TITLE
在leetcode网站导致代码复制不全

### ISSUE THREAD

**Issue by MrMingFang** [WindrunnerMax/TKScript#30]
chrome,油猴,仅运行这一个脚本
leetcode网站,比如下面这个
https://leetcode-cn.com/problems/min-stack/
右侧的代码复制出来会不全,只能复制出以下内容
class MinStack {
public:
    MinStack() {

    }
    
    void push(int val) {

    }
    
… */
关闭脚本后,复制正常

**Comment by WindrunnerMax** [comment]
确实有问题，我处理一下

**Comment by WindrunnerMax** [comment]
已经`ok`，更新`3.1.6`可解决
