### ISSUE TITLE
网站不生效优化

### ISSUE THREAD

**Issue by trainliang** [WindrunnerMax/TKScript#32]
地址：diyifanwen.com
问题：复制不生效

**Comment by WindrunnerMax** [comment]
正好我在处理，https://raw.githubusercontent.com/WindrunnerMax/TKScript/master/dist/copy.user.js 更新

**Comment by trainliang** [comment]
主要是指详情页的复制，[s.diyifanwen.com](https://s.diyifanwen.com/down/down.asp?url=https://www.diyifanwen.com/fanwen/biyejianding/4083645.html&obid=fanwen)

**Comment by WindrunnerMax** [comment]
这个已经处理好了
