### ISSUE TITLE
这个网站不能复制

### ISSUE THREAD

**Issue by jhzhou1997** [WindrunnerMax/TKScript#33]
https://www.cnrencai.com/

**Comment by WindrunnerMax** [comment]
已经处理了，等待同步更新或者点此立即更新 https://raw.githubusercontent.com/WindrunnerMax/TKScript/master/dist/copy.user.js

**Comment by bobvane** [comment]
http://www.kodiplayer.cn/

**Comment by WindrunnerMax** [comment]
> http://www.kodiplayer.cn/

已经处理了，等待同步更新或者点此立即更新 https://raw.githubusercontent.com/WindrunnerMax/TKScript/master/dist/copy.user.js
