### ISSUE TITLE
【Bug】插件导致语雀编辑异常

### ISSUE THREAD

**Issue by zhb0110** [WindrunnerMax/TKScript#36]
1. 无法换行
2. 无法输入'/'

**Comment by WindrunnerMax** [comment]
确实是插件导致的问题，我修正一下

**Comment by WindrunnerMax** [comment]
已经处理了，等待同步更新或者点此立即更新 https://raw.githubusercontent.com/WindrunnerMax/TKScript/master/dist/copy.user.js

**Comment by zhb0110** [comment]
好的，感谢
