### ISSUE TITLE
道客巴巴无法复制了

### ISSUE THREAD

**Issue by GXFQE** [WindrunnerMax/TKScript#38]
现在道客巴巴又没法复制了（复制按键突然消失了），希望能更改一下。

**Comment by GXFQE** [comment]
> 现在道客巴巴又没法复制了（复制按键突然消失了），希望能更改一下。

**Comment by GXFQE** [comment]
> > 现在道客巴巴又没法复制了（复制按键突然消失了），希望能更改一下。

**Comment by WindrunnerMax** [comment]
已经处理了，等待同步更新或者点此立即更新 https://raw.githubusercontent.com/WindrunnerMax/TKScript/master/dist/copy.user.js
