### ISSUE TITLE
似乎无效了？

### ISSUE THREAD

**Issue by hengz** [WindrunnerMax/TKScript#4]
百度文库，选中后没有出现脚本按钮。
![image](https://user-images.githubusercontent.com/3912180/109586449-3313ef80-7b40-11eb-92ec-2cfe71acf51c.png)

**Comment by WindrunnerMax** [comment]
给我个链接我试一下吧，或者试试脚本是不是还没更新到最新版？

**Comment by hengz** [comment]
比如这篇
https://wenku.baidu.com/view/9d3e3372b6360b4c2e3f5727a5e9856a57122668.html

**Comment by WindrunnerMax** [comment]
![image](https://user-images.githubusercontent.com/33169019/109607637-80ee1f00-7b63-11eb-9640-c2be313ff789.png)
我测试好像还好啊

**Comment by hengz** [comment]
重启浏览器后发现可以了，谢谢
Edge 88.0.705.81
