### ISSUE TITLE
破解复制

### ISSUE THREAD

**Issue by GXFQE** [WindrunnerMax/TKScript#40]
帮忙破解一下如下这个网站复制功能：https://eduai.baidu.com/view/a2eb01e4376baf1ffd4fad01（没有发现脚本冲突）

**Comment by WindrunnerMax** [comment]
已经处理了，等待同步更新或者点此立即更新 https://raw.githubusercontent.com/WindrunnerMax/TKScript/master/dist/copy.user.js
