### ISSUE TITLE
作者有空能不能把「简书」网站也加进去呢？

### ISSUE THREAD

**Issue by bjyh345** [WindrunnerMax/TKScript#41]
「简书」网站可以复制内容，但是会附加版权提示文字，如下：

这部分主要用来存储对象自身的运行时数据，如hashcode、gc分代年龄等。mark word的位长度为JVM的一个Word大小，也就是说32位JVM的Mark word为32位，64位JVM为64位。

作者：Hypercube
链接：https://www.jianshu.com/p/3d38cba67f8b
来源：简书
著作权归作者所有。商业转载请联系作者获得授权，非商业转载请注明出处。

如果有空，希望能添加对 简书 的支持，多谢！
还有，脚本很好用！感谢作者的付出！

**Comment by WindrunnerMax** [comment]
已经处理了，等待同步更新或者点此立即更新 https://raw.githubusercontent.com/WindrunnerMax/TKScript/master/dist/copy.user.js
