### ISSUE TITLE
腾讯文档不稳定

### ISSUE THREAD

**Issue by Squirrelllll** [WindrunnerMax/TKScript#42]
我最近发现在腾讯文档使用时经常显示不出复制按钮
用的是Firefox102.0（64位）tampermonkey正式版

**Comment by WindrunnerMax** [comment]
可能他改啥了吧，抽空我看看

**Comment by Squirrelllll** [comment]
好的，谢谢

**Comment by WindrunnerMax** [comment]
已经处理了，可以直接点这个更新 https://raw.githubusercontent.com/WindrunnerMax/TKScript/master/dist/copy.user.js， 或者等同步更新。
可以直接先更新试试，我感觉应该没问题了。

**Comment by Squirrelllll** [comment]
谢谢大佬
