### ISSUE TITLE
希望增加QQ邮箱的直接跳转

### ISSUE THREAD

**Issue by Hulkhao** [WindrunnerMax/TKScript#45]
QQ邮件 网页版，打开外部链接 会卡在https://mail.qq.com/cgi-bin/readtemplate?t=safety&check=false&gourl=******   的页面，等人为手动确认，略烦，希望能添加QQ邮箱的规则，感谢~~

**Comment by WindrunnerMax** [comment]
已经处理了，可以直接点这个更新 [site-director.user.js](https://raw.githubusercontent.com/WindrunnerMax/TKScript/master/dist/site-director.user.js) 或者等同步更新。

**Comment by Hulkhao** [comment]
已生效，非常感谢😄😄
