### ISSUE TITLE
问卷星

### ISSUE THREAD

**Issue by GXFQE** [WindrunnerMax/TKScript#46]
帮忙破解一下问卷星的复制功能
比如一下几个地址（第二个需先点击一次下一页按钮）
https://www.wjx.cn/vj/ru24cx9.aspx
https://ks.wjx.top/vm/Oj7YAHz.aspx

**Comment by WindrunnerMax** [comment]
明天处理一下

**Comment by WindrunnerMax** [comment]
已经处理了，可以直接点这个更新 [copy.user.js](https://raw.githubusercontent.com/WindrunnerMax/TKScript/master/dist/copy.user.js) 或者等同步更新。

**Comment by GXFQE** [comment]
太感谢了
