### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by JIQ1314an** [WindrunnerMax/TKScript#5]
只有部分网站可以，比如这个网站就复制不了，https://spider.doc88.com/p-40859595874829.html

**Comment by WindrunnerMax** [comment]
下次更新的时候再改改，可以先在代码的13行稍微改一下，不过我觉得对于你这个文档就算复制了也没有这个样式只有文字。
```javascript
// @include     *://www.doc88.com/*
```
改成
```javascript
// @include     *://*.doc88.com/*
```
![image](https://user-images.githubusercontent.com/33169019/109621438-f105a080-7b75-11eb-9da7-59cd99295f27.png)

**Comment by JIQ1314an** [comment]
嗯，好的

Czy <notifications@github.com> 于2021年3月2日周二 下午4:43写道：
