### ISSUE TITLE
无法复制知乎数学公式

### ISSUE THREAD

**Issue by tomgooo** [WindrunnerMax/TKScript#51]
例如 
https://zhuanlan.zhihu.com/p/279830836
https://zhuanlan.zhihu.com/p/26307123
全文复制下来的话，无法如以前一样，正常复制渲染后的数学公式
以前是可以直接复制图片url，如：
https://www.zhihu.com/equation?tex=%5Clim_%7Bx%5Crightarrow+x_0%7Df%28x%29%3DA%5CLeftrightarrow%5Cforall+x_n%5Crightarrow+x_0%28n%5Crightarrow+%5Cinfty%29%E6%81%92%E6%9C%89%5Clim_%7Bn%5Crightarrow%5Cinfty%7Df%28x_n%29%3DA+
现在只能复制为：
for∀ε>0,∃δ>0,when0<|x−x0|<δ,|f(x)−A|<ε
短公式还好，但是文章如果存在大量长公式，如：
|n→|=|n→⋅m→||m→|=|a(x−x0)+b(y−y0)||a2+b2|\begin{align} |\vec{n}|&=\frac{|\vec{n}\cdot\vec{m}|}{|\vec{m}|}\notag\\&=\frac{|a(x-x_0)+b(y-y_0)|}{|\sqrt{a^2+b^2}|} \end{align} \\\begin{align} |\vec{n}|&=\frac{|\vec{n}\cdot\vec{m}|}{|\vec{m}|}\notag\\&=\frac{|a(x-x_0)+b(y-y_0)|}{|\sqrt{a^2+b^2}|} \end{align} \\
会使复制效率严重降低。
希望能够得到您的建议和答复😀

**Comment by WindrunnerMax** [comment]
这块我还真不清楚，如果关了脚本依旧无法复制的话，应该是知乎做了限制，这块我得研究研究

**Comment by tomgooo** [comment]
好的，我可以提供一份以前的数学公式相关文章，这在Markdown编辑器里可以非常直观地阅览



# 归结原则（海涅（Heine）定理）


## 定理内容：

![[公式]](https://www.zhihu.com/equation?tex=%5Clim_%7Bx%5Crightarrow+x_0%7Df%28x%29%3DA%5CLeftrightarrow%5Cforall+x_n%5Crightarrow+x_0%28n%5Crightarrow+%5Cinfty%29%E6%81%92%E6%9C%89%5Clim_%7Bn%5Crightarrow%5Cinfty%7Df%28x_n%29%3DA+) 

## 证明：

![[公式]](https://www.zhihu.com/equation?tex=%28%5CRightarrow%29) 必要性：

由极限定义可得： ![[公式]](https://www.zhihu.com/equation?tex=for+%5Cforall+%5Cvarepsilon%3E0%2C%5Cexists%5Cdelta%3E0%2Cwhen0%3C%7Cx-x_0%7C%3C%5Cdelta%2C%7Cf%28x%29-A%7C%3C%5Cvarepsilon) 

由数列极限可知：对于上述 ![[公式]](https://www.zhihu.com/equation?tex=%5Cdelta) ,存在 ![[公式]](https://www.zhihu.com/equation?tex=N) ，当 ![[公式]](https://www.zhihu.com/equation?tex=n%3EN+) 时 ![[公式]](https://www.zhihu.com/equation?tex=0%3C%7Cx_n-x_0%7C%3C%5Cdelta) ,所以 ![[公式]](https://www.zhihu.com/equation?tex=%7Cf%28x_n%29-A%7C%3C%5Cvarepsilon) ,由此可得 ![[公式]](https://www.zhihu.com/equation?tex=%5Clim_%7Bn%5Crightarrow%5Cinfty%7Df%28x_n%29%3DA) 

------

![[公式]](https://www.zhihu.com/equation?tex=%28%5CLeftarrow%29) 充分性：

**条件**： ![[公式]](https://www.zhihu.com/equation?tex=%5Cforall+x_n%5Crightarrow+x_0%28n%5Crightarrow+%5Cinfty%29%E6%81%92%E6%9C%89%5Clim_%7Bn%5Crightarrow%5Cinfty%7Df%28x_n%29%3DA+) 
**结论**： ![[公式]](https://www.zhihu.com/equation?tex=%5Clim_%7Bx%5Crightarrow+x_0%7Df%28x%29%3DA) 

**证明思路**：利用反证法，**假设结论不成立**，然后证明结论不成立之后的必然成立的子结论，最后得到子结论不能和条件同时成立，由此得到假设不成立，因此结论成立，进而得到充分性证明。注意在充分性的证明中条件是永远成立的，所以只要得出条件不成立的假设都是错误假设。

**假设A**： ![[公式]](https://www.zhihu.com/equation?tex=%5Clim_%7Bx%5Crightarrow+x_0%7Df%28x%29%5Cne+A) 

由此推出**子结论**：对于**任意小**的 ![[公式]](https://www.zhihu.com/equation?tex=%5Cdelta) ,(这里隐含的意思就是对所有的 ![[公式]](https://www.zhihu.com/equation?tex=%5Cdelta) ），总存在**一点**![[公式]](https://www.zhihu.com/equation?tex=x%27%5Cin+U%5E0%28x_0%3B%5Cdelta%29)使得 ![[公式]](https://www.zhihu.com/equation?tex=%7Cf%28x%27%29-A%7C%3E%5Cvarepsilon) （注意这里也是对于该点成立的， ![[公式]](https://www.zhihu.com/equation?tex=x%27) 是一个点)

 这时我们只要证明在条件成立的情况下，子结论**不总是成立**的就可以了。因为只要假设A成立，子结论对于任何 ![[公式]](https://www.zhihu.com/equation?tex=%5Cdelta) 总是成立的，这时我们只要找到**一个反例**就可以证明假设错误了，为了达到这一目的，同时为了利用条件，我们就需要人为**构造出一个数列**。

由子结论可知，总有一点 ![[公式]](https://www.zhihu.com/equation?tex=x) 使 ![[公式]](https://www.zhihu.com/equation?tex=%7Cf%28x%29-A%7C%3E%5Cvarepsilon) 成立，这里我们通过调整 ![[公式]](https://www.zhihu.com/equation?tex=%5Cdelta) 来获得不同的 ![[公式]](https://www.zhihu.com/equation?tex=x) ，这里依次取 ![[公式]](https://www.zhihu.com/equation?tex=%5Cdelta%3D%5Cdelta%27%2C%5Cfrac%7B%5Cdelta%27%7D%7B2%7D%2C%5Cdots%2C%5Cfrac%7B%5Cdelta%27%7D%7Bn%7D%2C%5Cdots) ，由此构成数列 ![[公式]](https://www.zhihu.com/equation?tex=%5C%7Bx_n%5C%7D) ,因为 ![[公式]](https://www.zhihu.com/equation?tex=0%3C%7Cx_n-x_0%7C%3C%5Cfrac%7B%5Cdelta%27%7D%7Bn%7D) 故 ![[公式]](https://www.zhihu.com/equation?tex=%5Clim_%7Bn%5Crightarrow%5Cinfty%7Dx_n%3Dx_0) （迫敛性法则），同时由条件知道对于**任意**满足 ![[公式]](https://www.zhihu.com/equation?tex=%5Clim_%7Bn%5Crightarrow%5Cinfty%7Dx_n%3Dx_0) 这一条件的数列恒有 ![[公式]](https://www.zhihu.com/equation?tex=%5Clim_%7Bn%5Crightarrow%5Cinfty%7Df%28x_n%29%3DA) ，故 ![[公式]](https://www.zhihu.com/equation?tex=%7Cf%28x_n%29-A%7C%3C%5Cvarepsilon) 

但是**子结论**对**所有** ![[公式]](https://www.zhihu.com/equation?tex=x%27) （属于![[公式]](https://www.zhihu.com/equation?tex=%5C%7Bx_n%5C%7D))都是 ![[公式]](https://www.zhihu.com/equation?tex=%7Cf%28x%27%29-A%7C%3E%5Cvarepsilon) 两者相矛盾，也即二者矛盾，最终得出假设不成立。

注意：

- 这里构造的数列除了极限是 ![[公式]](https://www.zhihu.com/equation?tex=x_0) ,各项有可能相同，所以不存在单调性可言
- 这里的 ![[公式]](https://www.zhihu.com/equation?tex=%5Cdelta) 是可以随便取值的，也可以直接取 ![[公式]](https://www.zhihu.com/equation?tex=%5Cfrac%7B1%7D%7Bn%7D) 等

------

其实很多人对于[[海涅定理](https://www.zhihu.com/search?q=%E6%B5%B7%E6%B6%85%E5%AE%9A%E7%90%86&search_source=Entity&hybrid_search_source=Entity&hybrid_search_extra={%22sourceType%22%3A%22article%22%2C%22sourceId%22%3A%22279830836%22})](https://www.zhihu.com/search?q=海涅定理&search_source=Entity&hybrid_search_source=Entity&hybrid_search_extra={"sourceType"%3A"article"%2C"sourceId"%3A"279830836"})中充分性证明一直不能理解的点在于明明是要证明对于任何数列都成立，但是在证明过程中却只是证明了一种情况不成立就得出结论了，感觉好像逻辑上说不过去，但是事实上构造的这个数列只是为了证明条件了子结论是冲突的，而不是为了直接证明假设和结论是冲突，综上之所以会产生不能理解海涅定理充分性的证明主要是由于想错了证明的方向。



作者：一号村
链接：https://zhuanlan.zhihu.com/p/279830836
来源：知乎
著作权归作者所有。商业转载请联系作者获得授权，非商业转载请注明出处。

**Comment by WindrunnerMax** [comment]
我研究了下，他应该是换框架了，现在的DOM结构完全是由SVG呈现的，应该是搞不了

我建议还是找个这种类似的公式解析器，把公式先放到那里边解析一遍
