### ISSUE TITLE
无法复制大百科全书网页的文字

### ISSUE THREAD

**Issue by codercplus** [WindrunnerMax/TKScript#52]
![Snipaste_2022-08-05_11-51-44](https://user-images.githubusercontent.com/63757163/182998057-e9db0ce1-eb1a-4d00-87a4-7f0a3012d4ae.png)

问题网页：https://www.zgbk.com/ecph/search/result?SiteID=1&Alias=all&Query=%E9%9D%92%E8%B1%86

问题描述：1. 选中文字后，无法点击鼠标右键；2. 选中文字后按CTRL+C会弹出阻止对话框。

**Comment by WindrunnerMax** [comment]
已经处理了，可以直接点这个更新 [copy.user.js](https://raw.githubusercontent.com/WindrunnerMax/TKScript/master/dist/copy.user.js) 或者等同步更新。
