### ISSUE TITLE
增加石墨文档网站复制功能

### ISSUE THREAD

**Issue by raindog116** [WindrunnerMax/TKScript#53]
你好，最近用到石墨网站，请问能否增加其网站来适应插件啊

**Comment by raindog116** [comment]
网址是：https://shimo.im/

**Comment by WindrunnerMax** [comment]
还是给一个具体一点的的不能复制的链接吧

**Comment by WindrunnerMax** [comment]
上边着`75a0dc0`的标记有误，忽略这个信息。

**Comment by WindrunnerMax** [comment]
> 还是给一个具体一点的的不能复制的链接吧

这个不要忽略，给个具体的不能复制的链接才能处理

**Comment by raindog116** [comment]
你好，不好意思是我没有说清楚情况。我有看了一下，是在石墨企业版本才有的添加协作者时，其中的一个只能评论选项。所以我看到的链接只能我来查看。而我又不是企业版用好添加不了那个只能评论的选项。

**Comment by raindog116** [comment]
> > 还是给一个具体一点的的不能复制的链接吧
> 
> 这个不要忽略，给个具体的不能复制的链接才能处理

https://shimo.im/joinCompany/kmGXIFQcqdQzmHst?referer=link_team_invite&inviter=N9NE8L
看看这个链接可以不，刚刚搞了一个。

**Comment by raindog116** [comment]
> > 还是给一个具体一点的的不能复制的链接吧
> 
> 这个不要忽略，给个具体的不能复制的链接才能处理

看看这个链接可以吗 https://shimo.im/docs/B1Aw1d4Er2iddqm8/

**Comment by WindrunnerMax** [comment]
提示我
当前登录账号 没有权限访问这个文档

![image](https://user-images.githubusercontent.com/33169019/183553574-c71915ed-361b-4778-a06f-bf150989e74e.png)

**Comment by raindog116** [comment]
https://shimo.im/docs/B1Aw1d4Er2iddqm8/ 《不能复制测试链接》访问密码 cvcctc
试试这个呢？对石墨也不太熟，sorry！

**Comment by WindrunnerMax** [comment]
> https://shimo.im/docs/B1Aw1d4Er2iddqm8/ 《不能复制测试链接》访问密码 cvcctc 试试这个呢？对石墨也不太熟，sorry！

你可以先开个无痕模式然后打开测试下是不是能够正常复制，我试了试你这个链接是可以复制的

**Comment by raindog116** [comment]
> > https://shimo.im/docs/B1Aw1d4Er2iddqm8/ 《不能复制测试链接》访问密码 cvcctc 试试这个呢？对石墨也不太熟，sorry！
> 
> 你可以先开个无痕模式然后打开测试下是不是能够正常复制，我试了试你这个链接是可以复制的

嗯，我自己的开了一下看到是阅读模式，我刚设置了评论模式。让后就要求登录后才能访问了，你登录试试

**Comment by WindrunnerMax** [comment]
登录后就显示没权限访问

**Comment by WindrunnerMax** [comment]
或者你试试这个 https://greasyfork.org/zh-CN/scripts/439557-%E6%96%87%E6%9C%AC%E9%80%89%E4%B8%AD%E5%A4%8D%E5%88%B6-%E9%80%9A%E7%94%A8

注意看使用方法

**Comment by raindog116** [comment]
> 或者你试试这个 https://greasyfork.org/zh-CN/scripts/439557-%E6%96%87%E6%9C%AC%E9%80%89%E4%B8%AD%E5%A4%8D%E5%88%B6-%E9%80%9A%E7%94%A8
> 
> 注意看使用方法

终于可以了。之前我也是用的这个。这次三个都关闭后就可以复制了。非常感谢
