### ISSUE TITLE
希望增加小鹅通xiaoeknow.com网站/H5页面复制功能

### ISSUE THREAD

**Issue by heartwight** [WindrunnerMax/TKScript#54]
希望在H5页面上也能接触复制粘贴的限制
例如这个网站https://approlqfifz7374.h5.xiaoeknow.com/v1/course/text/i_6061ba54e4b0cd1ef51a8b08?type=2
谢谢作者大佬！！！

**Comment by WindrunnerMax** [comment]
额，要付费查看？

**Comment by heartwight** [comment]
> 额，要付费查看？

emmm...那我截图一下吧/捂脸
![image](https://user-images.githubusercontent.com/110757237/183278670-348e3ce4-5335-4fab-a0e8-28c74bb8533b.png)
![image](https://user-images.githubusercontent.com/110757237/183278780-b9ec7c36-f578-40b4-8b14-be59eb99ac00.png)
就是像这样的文章，不能复制文字惹~

**Comment by WindrunnerMax** [comment]
你试试这个 https://greasyfork.org/zh-CN/scripts/439557-%E6%96%87%E6%9C%AC%E9%80%89%E4%B8%AD%E5%A4%8D%E5%88%B6-%E9%80%9A%E7%94%A8

**Comment by WindrunnerMax** [comment]
> 你试试这个 https://greasyfork.org/zh-CN/scripts/439557-%E6%96%87%E6%9C%AC%E9%80%89%E4%B8%AD%E5%A4%8D%E5%88%B6-%E9%80%9A%E7%94%A8

注意看使用方法

**Comment by heartwight** [comment]
> > 你试试这个 https://greasyfork.org/zh-CN/scripts/439557-%E6%96%87%E6%9C%AC%E9%80%89%E4%B8%AD%E5%A4%8D%E5%88%B6-%E9%80%9A%E7%94%A8
> 
> 注意看使用方法

欧欧！我去试试！！谢谢大佬！！！

**Comment by WindrunnerMax** [comment]
客气了
