### ISSUE TITLE
百度阅读

### ISSUE THREAD

**Issue by GXFQE** [WindrunnerMax/TKScript#56]
添加一下百度阅读复制功能。
https://yuedu.baidu.com/ebook/f5d875126d1aff00bed5b9f3f90f76c660374cc2?pn=1&click_type=10010002&rf=https%3A%2F%2Fyuedu.baidu.com%2Fsearch%3Fword%3D%25C5%25D7%25CE%25EF%25CF%25DF%26pbook%3D0

**Comment by WindrunnerMax** [comment]
你这个链接我试了试直接就能够复制

**Comment by GXFQE** [comment]
我这里右键复制和Ctrl+C复制后，都无法把内容粘贴出来。

**Comment by WindrunnerMax** [comment]
我现在也不行了，刚才还行，那就处理下

**Comment by WindrunnerMax** [comment]
已经处理了，可以直接点这个更新 [copy.user.js](https://raw.githubusercontent.com/WindrunnerMax/TKScript/master/dist/copy.user.js) 或者等同步更新。
