### ISSUE TITLE
百度翻译

### ISSUE THREAD

**Issue by Traserve** [WindrunnerMax/TKScript#58]
大佬，百度翻译的文档翻译可否支持一下

**Comment by WindrunnerMax** [comment]
可以给个具体链接

**Comment by Traserve** [comment]
https://fanyi.baidu.com/mtpe/#/editor/quickImport
上传一份文档后复制翻译后文本

**Comment by WindrunnerMax** [comment]
已经处理了，可以直接点这个更新 [copy.user.js](https://raw.githubusercontent.com/WindrunnerMax/TKScript/master/dist/copy.user.js) 或者等同步更新。
