### ISSUE TITLE
知乎电子书不能复制

### ISSUE THREAD

**Issue by vpioe** [WindrunnerMax/TKScript#6]
链接：https://www.zhihu.com/pub/reader/119617413/chapter/1106576726997569536

没有出现提示气泡

感谢作者辛劳努力

**Comment by WindrunnerMax** [comment]
😄上课ing，下午下了课回去试试

**Comment by WindrunnerMax** [comment]
OK已经处理完成了，更新一下脚本就行了 https://greasyfork.org/zh-CN/scripts/405130
