### ISSUE TITLE
mihoyo网址更新

### ISSUE THREAD

**Issue by chuyueye** [WindrunnerMax/TKScript#61]
*://bbs.mihoyo.com/ys/obc/*
更改为
*://*.mihoyo.com/*

不知道为什么不扩大范围，误伤会有什么坏处吗

**Comment by WindrunnerMax** [comment]
已经处理了，可以直接点这个更新 [copy.user.js](https://raw.githubusercontent.com/WindrunnerMax/TKScript/master/dist/copy.user.js) 或者等同步更新。
