### ISSUE TITLE
css user-select: none更新

### ISSUE THREAD

**Issue by chuyueye** [WindrunnerMax/TKScript#62]
https://bbs.mihoyo.com/ys/article/27922519
这个网志中通过css（{-webkit-user-select:none;-moz-user-select:none;-ms-user-select:none;user-select:none}）
禁用了用户选择文字

**Comment by WindrunnerMax** [comment]
已经处理了，可以直接点这个更新 [copy.user.js](https://raw.githubusercontent.com/WindrunnerMax/TKScript/master/dist/copy.user.js) 或者等同步更新。
