### ISSUE TITLE
反馈：MBA智库不适用。

### ISSUE THREAD

**Issue by LIL-YAML** [WindrunnerMax/TKScript#7]
是会弹出app下载的框。

**Comment by WindrunnerMax** [comment]
给个链接我试一下吧

**Comment by WindrunnerMax** [comment]
> > 给个链接我试一下吧
> 
> https://wiki.mbalib.com/wiki/%E7%B4%A7%E7%BC%A9%E8%B4%A7%E5%B8%81%E6%94%BF%E7%AD%96
> 
> 你好开发大大。这是随机选的一个网站，一复制就会有一个弹窗的。

为啥我试了试这个链接没有弹窗呢😂

**Comment by WindrunnerMax** [comment]
随便找了个链接处理了一下，你可以试试 https://doc.mbalib.com/view/b06e89f92913b682a1f32c034a57d948.html  
然后你可以新安装一下版本试试了
