### ISSUE TITLE
一直弹窗功能受限

### ISSUE THREAD

**Issue by lzhxdsn** [WindrunnerMax/TKScript#71]
如图显示服务器压力过大要支付，github或者GreasyFork安装都是这个，扫码也扫不出来，不输密码又用不了![image](https://user-images.githubusercontent.com/66014395/191542897-6e26aac7-0b07-48e7-b29f-e353b54a1b0f.png)

**Comment by WindrunnerMax** [comment]
这个脚本从来都是免费的，你是被盗版骗了吧。。。

**Comment by WindrunnerMax** [comment]
https://windrunnermax.github.io/TKScript/copy.user.js
你点这个就能成功安装了。。。
