### ISSUE TITLE
不好意思 想问下为什么不弹复制窗口

### ISSUE THREAD

**Issue by xban12** [WindrunnerMax/TKScript#72]
![image](https://user-images.githubusercontent.com/77780051/191671368-d50bac40-8ea8-48f1-965a-ac110e86d6f3.png)

感觉不像是脚本冲突问题，关掉过其他的脚本试过了

然后应该也不是暴力猴的问题，我换稳定版油猴也不能用

出问题网页：https://wenku.baidu.com/view/8eff0f848762caaedd33d47f.html

**Comment by xban12** [comment]
然后就是测试了 无痕模式 + 登录状态下（禁用了其他所有扩展）也无效 
chrome版本104

**Comment by WindrunnerMax** [comment]
<img width="1528" alt="image" src="https://user-images.githubusercontent.com/33169019/191677796-c859a138-9ee0-4ee9-8205-9f26130e1b08.png">

**Comment by WindrunnerMax** [comment]
我测试是ok的

**Comment by xban12** [comment]
> 我测试是ok的

重启莫名好了 打扰了
