### ISSUE TITLE
https://www.xiexiebang.com/

### ISSUE THREAD

**Issue by iamfjun** [WindrunnerMax/TKScript#73]
您这个script我很期待，但是我装载后，https://www.xiexiebang.com/ 却仍提示。能否看看呢。

**Comment by WindrunnerMax** [comment]
或许你可以试试这个 https://windrunnermax.github.io/TKScript/copy-currency.user.js

**Comment by WindrunnerMax** [comment]
已适配，可点击更新 https://windrunnermax.github.io/TKScript/copy.user.js 或者等待脚本同步
