### ISSUE TITLE
https://www.baihuawen.cn/

### ISSUE THREAD

**Issue by SxitDark** [WindrunnerMax/TKScript#74]
使用通用脚本后复制功能仍被拦截，请适配，谢谢

**Comment by WindrunnerMax** [comment]
处理了下通用脚本，需要更新`1.1.1`版本，更新之后打开网站需要手动在左下角找到控制栏，手动启动

<img width="197" alt="image" src="https://user-images.githubusercontent.com/33169019/196962719-206e65a5-85cd-41db-90db-b436edad2a94.png">
