### ISSUE TITLE
https://juejin.cn/

### ISSUE THREAD

**Issue by MQPearth** [WindrunnerMax/TKScript#75]
求适配掘金

**Comment by WindrunnerMax** [comment]
具体一点，适配啥呀，此外给个具体的链接吧

**Comment by MQPearth** [comment]
抱歉

[文章地址](https://juejin.cn/post/7046575907275800590)

![image](https://user-images.githubusercontent.com/32632796/197464106-2bb5512d-3cbe-405e-9217-ad206baad67c.png)


点击复制代码, 需要登录才行

**Comment by WindrunnerMax** [comment]
抱歉，这种Hook按钮的功能实现有点不太好做，复制这个脚本主要是做类似于左边代码块鼠标拖拽无法选中复制这种功能的，如果这方面出问题了可以再提issue吧，这个Hook按钮的功能我得再看看

**Comment by MQPearth** [comment]
感谢
