### ISSUE TITLE
文本选中复制-希望新增网站https://www.php.cn/

### ISSUE THREAD

**Issue by zxyqq** [WindrunnerMax/TKScript#78]
https://www.php.cn/
php中文网-教程_手册_视频-免费php在线学习平台

**Comment by WindrunnerMax** [comment]
给一个具体点的网址吧，我简单试了下都能够复制

**Comment by zxyqq** [comment]
https://www.php.cn/be/go/441360.html
Go语言中处理json数据的方法-Golang-PHP中文网
提示要登录后复制

**Comment by WindrunnerMax** [comment]
已更新，需要`6.1.4`版本，可以等待同步或者直接在`Github`安装新版本，另外只是处理了可以手动选中代码块复制。
