### ISSUE TITLE
有一个小bug

### ISSUE THREAD

**Issue by GXFQE** [WindrunnerMax/TKScript#83]
百度文库Ctrl+C复制不了，只能点击复制按钮。

**Comment by GXFQE** [comment]
测试链接：https://wenku.baidu.com/view/d6660222598102d276a20029bd64783e09127d43?aggId=d6660222598102d276a20029bd64783e09127d43&fr=catalogMain&_wkts_=1670463716554

**Comment by WindrunnerMax** [comment]
其实这不算BUG啦，百度文库是个很复杂问题，再加上最初我没设计与按键交互的数据流，就是现在这个情况啦
