### ISSUE TITLE
复制过程中有一个小bug

### ISSUE THREAD

**Issue by ConstructiveLine** [WindrunnerMax/TKScript#84]
在豆丁网进行复制时出现标点符号被空格取代的现象
![image](https://user-images.githubusercontent.com/117820227/208276150-19f08cbe-bbc4-42f4-b5c9-8b71d101027d.png)
在word中显示如下
<img width="349" alt="image" src="https://user-images.githubusercontent.com/117820227/208276195-6f5d12a9-07c6-4cdf-991e-4ecdd8586979.png">
测试连接
https://www.docin.com/p-365434989.html#:~:text=%E6%88%91%E5%9B%BD%E5%91%A8%E8%BE%B9%E5%AE%89%E5%85%A8%E7%8E%AF%E5%A2%83%E9%9D%A2%E4%B8%B4%E7%9A%84%E5%A8%81%E8%83%81%E5%92%8C%E6%8C%91%E6%88%98%E4%B8%BB%E8%A6%81%E6%98%AF%EF%BC%9A%EF%BC%88%E4%B8%80%EF%BC%89%E7%BE%8E%E5%9B%BD%E7%9A%84%E9%9C%B8%E6%9D%83%E4%B8%BB%E4%B9%89%E5%92%8C%E5%86%B7%E6%88%98%E6%80%9D%E7%BB%B4%E5%AF%B9%E6%88%91%E5%9B%BD%E5%91%A8%E8%BE%B9%E5%AE%89%E5%85%A8%E7%9A%84%E5%BD%B1%E5%93%8D%E6%98%AF%E7%BB%BC%E5%90%88%E6%80%A7%20%E7%9A%84%E3%80%81%E9%95%BF%E6%9C%9F%E7%9A%84,%E4%B8%BA%E5%BB%B6%E7%BC%93%E4%B8%AD%E5%9B%BD%E6%88%90%E4%B8%BA%E4%B8%96%E7%95%8C%E5%BC%BA%E5%9B%BD%E7%9A%84%E8%84%9A%E6%AD%A5%EF%BC%8C%E7%BE%8E%E5%9B%BD%E5%AF%B9%E6%88%91%E5%9B%BD%E5%9C%A8%E6%94%BF%E6%B2%BB%E3%80%81%E7%BB%8F%E6%B5%8E%E3%80%81%E5%86%9B%E4%BA%8B%E7%AD%89%20%E6%96%B9%E9%9D%A2%EF%BC%8C%E5%A4%84%E5%A4%84%E5%88%B6%E9%80%A0%E4%BA%8B%E7%AB%AF%EF%BC%8C%E7%94%9A%E8%87%B3%E9%BC%93%E5%8A%A8%E3%80%81%E5%94%86%E4%BD%BF%E6%88%91%E5%91%A8%E8%BE%B9%E5%9B%BD%E5%AE%B6%E4%B8%8E%E6%88%91%E5%AF%B9%E6%8A%97%EF%BC%8C%E4%BB%8E%E8%80%8C%E6%88%90%20%E4%B8%BA%E6%88%91%E5%9B%BD%E5%91%A8%E8%BE%B9%E5%AE%89%E5%85%A8%E7%8E%AF%E5%A2%83%E4%B8%AD%E5%AF%B9%E6%88%91%E6%BD%9C%E5%9C%A8%E5%A8%81%E8%83%81%E6%9C%80%E5%A4%A7%E7%9A%84%E5%9B%BD%E5%AE%B6%E3%80%82

**Comment by WindrunnerMax** [comment]
我看了下，这是豆丁网绘制这个画板时的问题，我也没招了

**Comment by ConstructiveLine** [comment]
这样啊，还是很感谢您

**Comment by WindrunnerMax** [comment]
您客气了，这个issue我先关了~
