### ISSUE TITLE
希望可以连夜安排，明天中午要用到

### ISSUE THREAD

**Issue by zhushixi** [WindrunnerMax/TKScript#85]
作者大大你好，这个考试库https://www.examcoo.com/网址里面的考试考题不可以复制呀。比如https://www.examcoo.com/editor/do/view/id/157037还有https://www.examcoo.com/editor/do/exercise/pid/157037类似于这两个求求了哥们or姐姐求求了

**Comment by WindrunnerMax** [comment]
🐑了，发高烧干不动了，你可以试试通用版

**Comment by WindrunnerMax** [comment]
已支持，需要v6.1.7版本
