### ISSUE TITLE
希望能适配知乎电子书的页面

### ISSUE THREAD

**Issue by SrSh-notme** [WindrunnerMax/TKScript#86]
老板，你这个脚本太好用了。但是知乎电子书阅读的页面不能用。win11 edge 未出现复制按钮，希望能适配。

https://www.zhihu.com/pub/reader/119601575/chapter/1092470252998324224

**Comment by WindrunnerMax** [comment]
已修复，需要`6.1.8`版本，直接`Ctrl+C`复制即可
