### ISSUE TITLE
CSDN 貌似不管用了

### ISSUE THREAD

**Issue by stefenson** [WindrunnerMax/TKScript#87]

**Comment by WindrunnerMax** [comment]
我测试好像没问题，这个脚本不处理那个登陆后复制按钮，只是可以手动选择代码然后`Ctrl+C`复制

**Comment by stefenson** [comment]
> 我测试好像没问题，这个脚本不处理那个登陆后复制按钮，只是可以手动选择代码然后`Ctrl+C`复制

我这边测试是确认脚本为打开状态，并且手动添加了 csdn 域名的匹配，还是无法选中复制。

**Comment by Chengfanfu** [comment]
大佬，[https://www.xiangqiqipu.com/](https://greasyfork.org/zh-CN/scripts/28497-%E7%BD%91%E9%A1%B5%E9%99%90%E5%88%B6%E8%A7%A3%E9%99%A4-%E6%94%B9/discussions/167196)，能否解除一下这个网页的复制限制

**Comment by stefenson** [comment]
> 可以提供个链接，或者你再试试是不是脚本冲突了。

找到原因了，我油猴挂了……

**Comment by WindrunnerMax** [comment]
> 大佬，[https://www.xiangqiqipu.com/](https://greasyfork.org/zh-CN/scripts/28497-%E7%BD%91%E9%A1%B5%E9%99%90%E5%88%B6%E8%A7%A3%E9%99%A4-%E6%94%B9/discussions/167196)，能否解除一下这个网页的复制限制

可以更新到6.1.10版本
