### ISSUE TITLE
请求适配 Apple Music 网页版

### ISSUE THREAD

**Issue by morningcheng** [WindrunnerMax/TKScript#92]
希望能适配 Apple Music 网页版，在此先感谢作者

https://beta.music.apple.com/jp/
注：此为 Apple Music Beta 网页版，直接访问会跳转到国内

https://music.apple.com/jp/
注：Apple Music 网页版，直接访问会强制唤醒 Apple Music 桌面端 App

**Comment by WindrunnerMax** [comment]
要不你发个具体的链接，我不清楚你要搞哪部分内容，比如某首歌的歌词？

**Comment by morningcheng** [comment]
这个是其中一张专辑的页面的链接
https://beta.music.apple.com/jp/album/bootleg/1538275115

网页版目前没有歌词，我只是想能够复制专辑中的歌曲名、歌手名
Apple Music 日区对某些歌曲名的特殊样式都是和官方保持一致的，修改参考很方便
原先是可以选择复制歌曲名之类的信息的，但后来 Apple 加了限制
目前专辑页面只能复制专辑名，歌手名还需要点进主页才能复制，更别说歌曲名了

**Comment by WindrunnerMax** [comment]
我似乎因为没有会员被重定向了，要不你先尝试一下通用版本

**Comment by WindrunnerMax** [comment]
文本选中复制-通用	[详情](https://github.com/WindrunnerMax/TKScript/blob/master/packages/copy-currency/README.md)	[安装](https://windrunnermax.github.io/TKScript/copy-currency.user.js)

**Comment by WindrunnerMax** [comment]
我试了下通用脚本是可以的，你应该是没在右下角开启 [插件详情](https://github.com/WindrunnerMax/TKScript/blob/master/packages/copy-currency/README.md)

**Comment by morningcheng** [comment]
都启用了，但是框内部分还是没法选中复制

![CleanShot 2023-04-05 at 02 39 48@2x](https://user-images.githubusercontent.com/22173147/229888213-3bc910fb-6338-4024-9d25-8a39c5c661bb.png)

**Comment by WindrunnerMax** [comment]
确实，他还有一个拖拽的响应，但是我也没太看明白怎么做的
