### ISSUE TITLE
飞书文档如何添加可复制

### ISSUE THREAD

**Issue by Jj225714** [WindrunnerMax/TKScript#97]
链接   https://vxcni1izs8.feishu.cn/docx/NN7bd0s22oSRtyxmdVhc6aUhn7g

**Comment by WindrunnerMax** [comment]
可以用通用版本处理这个问题 文本选中复制-通用 [详情](https://github.com/WindrunnerMax/TKScript/blob/master/packages/copy-currency/README.md) [安装](https://windrunnermax.github.io/TKScript/copy-currency.user.js)，注意看详情使用信息，需要左下角手动开启才可以
